if(sessionStorage.getItem('ba_admin')!=='1')location.href='admin-login.html';
let products=JSON.parse(localStorage.getItem('ba_products')||'[]');let orders=JSON.parse(localStorage.getItem('ba_orders')||'[]');let editId=null;
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function save(){localStorage.setItem('ba_products',JSON.stringify(products))}function stats(){$('#sProducts').textContent=products.length;$('#sOrders').textContent=orders.length;$('#sNew').textContent=orders.filter(x=>x.status==='new').length;$('#sLow').textContent=products.filter(x=>Number(x.stock)<=5).length}
function renderProducts(){let q=$('#productSearch').value.toLowerCase();$('#productsBody').innerHTML=products.filter(p=>p.name.toLowerCase().includes(q)).map(p=>`<tr><td>${p.image?`<img class="thumb" src="${esc(p.image)}">`:'—'}</td><td>${esc(p.name)}</td><td>${esc(p.cat)}</td><td>${Number(p.price).toFixed(2)} د</td><td>${p.stock}</td><td>${p.active===false?'مخفي':'ظاهر'}</td><td><div class="actions"><button class="edit" data-edit="${p.id}">تعديل</button><button class="hide" data-toggle="${p.id}">${p.active===false?'إظهار':'إخفاء'}</button><button class="delete" data-delete="${p.id}">حذف</button></div></td></tr>`).join('')||'<tr><td colspan="7">لا توجد منتجات</td></tr>'}
const labels={new:'جديد',contacted:'تم التواصل',confirmed:'مؤكد',shipped:'تم الشحن',cancelled:'ملغى'};
function renderOrders(){let q=$('#orderSearch').value.toLowerCase();$('#ordersBody').innerHTML=orders.filter(o=>(o.name+' '+o.phone+' '+o.city).toLowerCase().includes(q)).map(o=>`<tr><td>${esc(o.name)}</td><td><a href="tel:${esc(o.phone)}">${esc(o.phone)}</a></td><td>${esc(o.city)}</td><td>${Number(o.total).toFixed(2)} د</td><td>${(o.items||[]).map(i=>esc(i.name)+' × '+i.qty).join('<br>')}</td><td><select class="status" data-status="${o.id}">${Object.entries(labels).map(([k,v])=>`<option value="${k}" ${o.status===k?'selected':''}>${v}</option>`).join('')}</select></td></tr>`).join('')||'<tr><td colspan="6">لا توجد طلبات</td></tr>'}
function reset(){editId=null;$('#formTitle').textContent='إضافة منتج';$('#saveProduct').textContent='إضافة المنتج';$('#cancel').hidden=true;$('#pName').value='';$('#pPrice').value='';$('#pStock').value='';$('#pImage').value='';$('#pFile').value='';$('#pDesc').value='';$('#pCat').value='سلاسل';$('#pActive').checked=true}
$('#saveProduct').onclick=()=>{let name=$('#pName').value.trim();if(!name){$('#formMsg').textContent='اكتب اسم المنتج.';return}let data={id:editId||'p'+Date.now(),name,cat:$('#pCat').value,price:Number($('#pPrice').value||0),stock:Number($('#pStock').value||0),image:$('#pImage').value.trim(),description:$('#pDesc').value.trim(),active:$('#pActive').checked};let file=$('#pFile').files[0];if(file){const r=new FileReader();r.onload=()=>{data.image=r.result;commit(data)};r.readAsDataURL(file)}else commit(data)};
function commit(data){if(editId){const i=products.findIndex(p=>p.id===editId);products[i]=data}else products.unshift(data);save();reset();$('#formMsg').textContent='تم الحفظ بنجاح.';renderProducts();stats()}
$('#cancel').onclick=reset;$('#productSearch').oninput=renderProducts;$('#orderSearch').oninput=renderOrders;
document.addEventListener('click',e=>{const ed=e.target.closest('[data-edit]');if(ed){let p=products.find(x=>x.id===ed.dataset.edit);if(!p)return;editId=p.id;$('#formTitle').textContent='تعديل المنتج';$('#saveProduct').textContent='حفظ التعديل';$('#cancel').hidden=false;$('#pName').value=p.name;$('#pCat').value=p.cat;$('#pPrice').value=p.price;$('#pStock').value=p.stock;$('#pImage').value=p.image?.startsWith('data:')?'':(p.image||'');$('#pDesc').value=p.description||'';$('#pActive').checked=p.active!==false;scrollTo({top:0,behavior:'smooth'})}const tg=e.target.closest('[data-toggle]');if(tg){let p=products.find(x=>x.id===tg.dataset.toggle);p.active=p.active===false;save();renderProducts();stats()}const del=e.target.closest('[data-delete]');if(del&&confirm('حذف المنتج؟')){products=products.filter(x=>x.id!==del.dataset.delete);save();renderProducts();stats()}});
document.addEventListener('change',e=>{const s=e.target.closest('[data-status]');if(s){let o=orders.find(x=>x.id===s.dataset.status);if(o)o.status=s.value;localStorage.setItem('ba_orders',JSON.stringify(orders));stats()}});$('#logout').onclick=()=>{sessionStorage.removeItem('ba_admin');location.href='admin-login.html'};stats();renderProducts();renderOrders();
