let supabaseClient=null;let products=[];let cart=JSON.parse(localStorage.getItem('cart')||'[]');
function initClient(){if(window.SUPABASE_URL&&window.SUPABASE_ANON_KEY&&window.supabase){supabaseClient=window.supabase.createClient(window.SUPABASE_URL,window.SUPABASE_ANON_KEY)}return !!supabaseClient}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function updateCartCount(){document.getElementById('cartCount').textContent=cart.reduce((s,x)=>s+x.qty,0)}
function toast(t){let x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function add(p){let i=cart.findIndex(x=>x.id===p.id);if(i>=0)cart[i].qty++;else cart.push({...p,qty:1});localStorage.setItem('cart',JSON.stringify(cart));updateCartCount();toast('تمت إضافة المنتج إلى السلة ✅')}
function render(){let grid=document.getElementById('productsGrid');grid.innerHTML=products.map(p=>`<article class="card"><div class="photo">${p.image_url?`<img src="${esc(p.image_url)}" alt="${esc(p.name)}">`:'لا توجد صورة'}</div><div class="cardbody"><h3>${esc(p.name)}</h3><p class="desc">${esc(p.description)}</p><div class="price">${Number(p.price).toFixed(2)} درهم</div><small>المخزون: ${p.stock}</small><div style="margin-top:12px"><button class="btn gold" ${p.stock<=0?'disabled':''} onclick='add(${JSON.stringify(p).replace(/'/g,"&#39;")})'>${p.stock<=0?'نفد المخزون':'أضف للسلة'}</button></div></div></article>`).join('')}
async function load(){let status=document.getElementById('status');if(!initClient()){status.textContent='ضع بيانات Supabase في config.js أولًا. يمكنك معاينة التصميم، لكن المنتجات والطلبات تحتاج قاعدة بيانات.';products=[];render();return}let r=await supabaseClient.from('products').select('*').eq('active',true).order('created_at',{ascending:false});if(r.error){status.textContent='تعذر تحميل المنتجات: '+r.error.message;return}products=r.data||[];status.hidden=products.length>0;if(!products.length)status.textContent='لا توجد منتجات حاليًا. أضف المنتجات من لوحة Admin.';render()}
document.getElementById('refreshBtn').onclick=load;updateCartCount();load();
